#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
from typing import Any, Dict, List

import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_jsonl", type=str, required=True, help="Path to JSONL generated by build_synth_context_idk.py")
    ap.add_argument("--output_dir", type=str, default="outputs/qwen3_small_idk")
    ap.add_argument("--model_name", type=str, default="Qwen/Qwen3-0.6B", help="Smallest Qwen3 base model name")
    ap.add_argument("--max_seq_len", type=int, default=2048)
    ap.add_argument(
        "--prompt_template",
        type=str,
        default="[query_start]{query}[query_end][context_start]{context}[context_end][answer_start]",
        help="Template for prompt (no answer).",
    )
    ap.add_argument(
        "--answer_end",
        type=str,
        default="[answer_end]",
        help="Answer end marker appended after answer text.",
    )

    ap.add_argument("--per_device_train_batch_size", type=int, default=2)
    ap.add_argument("--gradient_accumulation_steps", type=int, default=8)
    ap.add_argument("--learning_rate", type=float, default=2e-5)
    ap.add_argument("--num_train_epochs", type=float, default=1.0)
    ap.add_argument("--weight_decay", type=float, default=0.0)
    ap.add_argument("--warmup_ratio", type=float, default=0.03)
    ap.add_argument("--lr_scheduler_type", type=str, default="cosine")
    ap.add_argument("--logging_steps", type=int, default=10)
    ap.add_argument("--save_steps", type=int, default=500)
    ap.add_argument("--save_total_limit", type=int, default=2)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--report_to", type=str, default="none")
    ap.add_argument("--ddp_backend", type=str, default="nccl")
    ap.add_argument("--ddp_find_unused_parameters", action="store_true", help="Enable DDP find_unused_parameters")

    ap.add_argument("--bf16", action="store_true", help="Use bfloat16 if supported")
    ap.add_argument("--fp16", action="store_true", help="Use float16")
    ap.add_argument("--gradient_checkpointing", action="store_true", help="Enable gradient checkpointing")

    ap.add_argument("--use_lora", action="store_true", help="Enable LoRA fine-tuning (requires peft)")
    ap.add_argument("--lora_r", type=int, default=8)
    ap.add_argument("--lora_alpha", type=int, default=16)
    ap.add_argument("--lora_dropout", type=float, default=0.05)
    ap.add_argument(
        "--lora_target_modules",
        type=str,
        default="q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj",
        help="Comma-separated target module names for LoRA",
    )

    ap.add_argument("--filter_long", action="store_true", default=True, help="Drop samples with prompt_len >= max_seq_len")

    return ap.parse_args()


class AnswerOnlyCollator:
    def __init__(
        self,
        tokenizer: AutoTokenizer,
        max_length: int,
        prompt_template: str,
        answer_end: str,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.prompt_template = prompt_template
        self.answer_end = answer_end

    def _build_prompt(self, query: str, context: str) -> str:
        return self.prompt_template.format(query=query, context=context)

    def _build_full(self, query: str, context: str, answer: str) -> str:
        return f"{self._build_prompt(query, context)}{answer}{self.answer_end}"

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, torch.Tensor]:
        prompts = [self._build_prompt(ex["query"], ex["context"]) for ex in batch]
        texts = [
            self._build_full(ex["query"], ex["context"], ex["answer"])
            for ex in batch
        ]

        enc = self.tokenizer(
            texts,
            add_special_tokens=False,
            padding=True,
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt",
        )
        input_ids = enc["input_ids"]
        attention_mask = enc["attention_mask"]

        prompt_enc = self.tokenizer(
            prompts,
            add_special_tokens=False,
            padding=False,
            truncation=True,
            max_length=self.max_length,
            return_tensors=None,
        )
        prompt_lens = [len(ids) for ids in prompt_enc["input_ids"]]

        labels = input_ids.clone()

        for i, pl in enumerate(prompt_lens):
            if pl >= labels.size(1):
                labels[i, :] = -100
            else:
                labels[i, :pl] = -100

        labels[attention_mask == 0] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


def main() -> None:
    args = parse_args()

    tokenizer = AutoTokenizer.from_pretrained(args.model_name)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    ds = load_dataset("json", data_files=args.data_jsonl, split="train")
    if args.filter_long:
        def keep_ex(ex: Dict[str, Any]) -> bool:
            prompt = args.prompt_template.format(query=ex["query"], context=ex["context"])
            prompt_ids = tokenizer(
                prompt,
                add_special_tokens=False,
                truncation=True,
                max_length=args.max_seq_len,
            )["input_ids"]
            return len(prompt_ids) < args.max_seq_len - 1

        ds = ds.filter(keep_ex)

    dtype = None
    if args.bf16:
        dtype = torch.bfloat16
    elif args.fp16:
        dtype = torch.float16

    model = AutoModelForCausalLM.from_pretrained(
        args.model_name,
        torch_dtype=dtype,
    )

    if args.use_lora:
        from peft import LoraConfig, TaskType, get_peft_model

        target_modules = [s.strip() for s in args.lora_target_modules.split(",") if s.strip()]
        lora_cfg = LoraConfig(
            r=args.lora_r,
            lora_alpha=args.lora_alpha,
            lora_dropout=args.lora_dropout,
            target_modules=target_modules,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
        )
        model = get_peft_model(model, lora_cfg)
        model.enable_input_require_grads()

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()

    collator = AnswerOnlyCollator(
        tokenizer=tokenizer,
        max_length=args.max_seq_len,
        prompt_template=args.prompt_template,
        answer_end=args.answer_end,
    )

    train_args = TrainingArguments(
        output_dir=args.output_dir,
        per_device_train_batch_size=args.per_device_train_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        weight_decay=args.weight_decay,
        warmup_ratio=args.warmup_ratio,
        lr_scheduler_type=args.lr_scheduler_type,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        report_to=args.report_to,
        seed=args.seed,
        bf16=args.bf16,
        fp16=args.fp16,
        remove_unused_columns=False,
        optim="adamw_torch",
        ddp_backend=args.ddp_backend,
        ddp_find_unused_parameters=args.ddp_find_unused_parameters,
    )

    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=ds,
        data_collator=collator,
    )

    trainer.train()
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)


if __name__ == "__main__":
    main()
