#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
RL training on HotpotQA for reasoning+answer traces.

Supports:
  - GRPO (group-normalized policy gradient with KL regularization)
  - CISPO (clipped importance objective with KL regularization)

Reward:
  - format reward: 0/1 for presence/order of <think>, [answer_start], [answer_end]
  - exact-match reward: 0/1 against HotpotQA gold answer
  - total = format_weight * format + em_weight * em
"""

import argparse
import copy
import inspect
import json
import math
import os
import random
import re
import string
from collections import Counter, defaultdict
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

import torch
from datasets import Dataset, load_dataset
from torch.optim import AdamW
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer


SPECIAL_META_RE = re.compile(r"<\|[^>]+?\|>")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Train Qwen with GRPO/CISPO on HotpotQA using reasoning+answer format rewards."
    )

    ap.add_argument("--model_name_or_path", type=str, required=True)
    ap.add_argument("--reference_model_name_or_path", type=str, default="", help="Defaults to --model_name_or_path")
    ap.add_argument("--trust_remote_code", action="store_true")
    ap.add_argument("--local_files_only", action="store_true")
    ap.add_argument("--device", type=str, default="cuda")
    ap.add_argument("--dtype", type=str, default="bfloat16", choices=["auto", "float16", "bfloat16", "float32"])

    ap.add_argument("--dataset_name", type=str, default="hotpot_qa")
    ap.add_argument("--dataset_config", type=str, default="distractor")
    ap.add_argument("--train_split", type=str, default="train")
    ap.add_argument("--eval_split", type=str, default="validation")
    ap.add_argument("--max_train_examples", type=int, default=0, help="0 means all")
    ap.add_argument("--max_eval_examples", type=int, default=2000, help="0 means all")
    ap.add_argument("--context_mode", type=str, default="all", choices=["all", "gold_titles", "supporting"])
    ap.add_argument("--max_context_chars", type=int, default=6000)

    ap.add_argument("--algorithm", type=str, default="grpo", choices=["grpo", "cispo"])
    ap.add_argument("--num_steps", type=int, default=1000)
    ap.add_argument("--prompts_per_step", type=int, default=8)
    ap.add_argument("--group_size", type=int, default=4)
    ap.add_argument("--learning_rate", type=float, default=1e-6)
    ap.add_argument("--weight_decay", type=float, default=0.0)
    ap.add_argument("--grad_clip_norm", type=float, default=1.0)
    ap.add_argument("--beta_kl", type=float, default=0.02)
    ap.add_argument("--cispo_clip_eps", type=float, default=0.2)
    ap.add_argument("--adv_eps", type=float, default=1e-5)

    ap.add_argument("--format_reward_weight", type=float, default=1.0)
    ap.add_argument("--em_reward_weight", type=float, default=1.0)

    ap.add_argument(
        "--prompt_template",
        type=str,
        default="[context_start]{context}[context_end][query_start]{query}[query_end]",
        help="Context/query structure aligned with SFT setup. Answer markers are generated by model.",
    )
    ap.add_argument(
        "--format_instruction",
        type=str,
        default=(
            "Return exactly this format and nothing else: "
            "<think>brief reasoning</think>[answer_start]final short answer[answer_end]"
        ),
    )
    ap.add_argument("--think_open_token", type=str, default="<think>")
    ap.add_argument("--think_close_token", type=str, default="</think>")
    ap.add_argument("--answer_start_token", type=str, default="[answer_start]")
    ap.add_argument("--answer_end_token", type=str, default="[answer_end]")

    ap.add_argument("--max_prompt_tokens", type=int, default=2048)
    ap.add_argument("--max_new_tokens", type=int, default=192)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--top_p", type=float, default=0.95)
    ap.add_argument("--top_k", type=int, default=20)

    ap.add_argument("--log_every", type=int, default=10)
    ap.add_argument("--eval_every", type=int, default=100)
    ap.add_argument("--eval_prompts", type=int, default=256)
    ap.add_argument("--save_every", type=int, default=200)
    ap.add_argument("--output_dir", type=str, required=True)
    ap.add_argument("--seed", type=int, default=42)

    return ap.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def normalize_answer(text: str) -> str:
    def remove_articles(s: str) -> str:
        return re.sub(r"\b(a|an|the)\b", " ", s)

    def remove_punc(s: str) -> str:
        table = str.maketrans("", "", string.punctuation)
        return s.translate(table)

    def white_space_fix(s: str) -> str:
        return " ".join(s.split())

    return white_space_fix(remove_articles(remove_punc(text.lower())))


def exact_match(prediction: str, gold: str) -> float:
    return 1.0 if normalize_answer(prediction) == normalize_answer(gold) else 0.0


def strip_meta(text: str) -> str:
    text = SPECIAL_META_RE.sub(" ", text)
    text = text.replace("<s>", " ").replace("</s>", " ")
    return re.sub(r"\s+", " ", text).strip()


def parse_context_field(raw: Any) -> List[Tuple[str, List[str]]]:
    out: List[Tuple[str, List[str]]] = []
    if isinstance(raw, dict):
        titles = raw.get("title") or []
        sents = raw.get("sentences") or []
        for title, sent_list in zip(titles, sents):
            if isinstance(sent_list, str):
                sent_list = [sent_list]
            if not isinstance(sent_list, list):
                sent_list = []
            out.append((str(title), [str(x) for x in sent_list]))
        return out

    if isinstance(raw, list):
        for item in raw:
            title = ""
            sent_list: List[str] = []
            if isinstance(item, (list, tuple)) and len(item) >= 2:
                title = str(item[0])
                if isinstance(item[1], str):
                    sent_list = [item[1]]
                elif isinstance(item[1], list):
                    sent_list = [str(x) for x in item[1]]
            elif isinstance(item, dict):
                title = str(item.get("title") or "")
                s = item.get("sentences") or item.get("sentence") or []
                if isinstance(s, str):
                    sent_list = [s]
                elif isinstance(s, list):
                    sent_list = [str(x) for x in s]
            if title or sent_list:
                out.append((title, sent_list))
    return out


def parse_supporting_facts(raw: Any) -> Tuple[Set[Tuple[str, int]], Set[str]]:
    pairs: Set[Tuple[str, int]] = set()
    titles: Set[str] = set()
    if isinstance(raw, dict):
        raw_titles = raw.get("title") or []
        raw_ids = raw.get("sent_id") or []
        for title, sid in zip(raw_titles, raw_ids):
            try:
                sid_int = int(sid)
            except Exception:
                continue
            t = str(title)
            pairs.add((t, sid_int))
            titles.add(t)
        return pairs, titles

    if isinstance(raw, list):
        for item in raw:
            if not isinstance(item, (list, tuple)) or len(item) < 2:
                continue
            title = str(item[0])
            try:
                sid_int = int(item[1])
            except Exception:
                continue
            pairs.add((title, sid_int))
            titles.add(title)
    return pairs, titles


def format_doc(title: str, sentences: Sequence[str]) -> str:
    text = " ".join(x.strip() for x in sentences if str(x).strip())
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return ""
    if title.strip():
        return f"{title.strip()}\n{text}"
    return text


def build_hotpot_context(example: Dict[str, Any], mode: str, max_context_chars: int) -> str:
    docs = parse_context_field(example.get("context"))
    sf_pairs, sf_titles = parse_supporting_facts(example.get("supporting_facts"))

    selected: List[Tuple[str, List[str]]] = []
    if mode == "all":
        selected = docs
    elif mode == "gold_titles":
        selected = [(title, sents) for title, sents in docs if title in sf_titles]
        if not selected:
            selected = docs
    else:
        by_title: Dict[str, List[Tuple[int, str]]] = defaultdict(list)
        for title, sents in docs:
            for i, sent in enumerate(sents):
                if (title, i) in sf_pairs:
                    by_title[title].append((i, sent))
        for title, _ in docs:
            if title not in by_title:
                continue
            ranked = sorted(by_title[title], key=lambda t: t[0])
            selected.append((title, [x[1] for x in ranked]))
        if not selected:
            selected = docs

    blocks: List[str] = []
    for title, sents in selected:
        block = format_doc(title=title, sentences=sents)
        if block:
            blocks.append(block)
    ctx = "\n\n".join(blocks).strip()
    if max_context_chars > 0 and len(ctx) > max_context_chars:
        return ctx[:max_context_chars].rstrip()
    return ctx


class HotpotReasoningEnv:
    def __init__(
        self,
        dataset_name: str,
        dataset_config: str,
        train_split: str,
        eval_split: str,
        context_mode: str,
        max_context_chars: int,
        prompt_template: str,
        format_instruction: str,
        max_train_examples: int,
        max_eval_examples: int,
        seed: int,
    ) -> None:
        self.prompt_template = prompt_template
        self.format_instruction = format_instruction.strip()
        self.rng = random.Random(seed)
        self.train_data = self._load(
            dataset_name,
            dataset_config,
            split=train_split,
            context_mode=context_mode,
            max_context_chars=max_context_chars,
            max_examples=max_train_examples,
            seed=seed,
        )
        self.eval_data = self._load(
            dataset_name,
            dataset_config,
            split=eval_split,
            context_mode=context_mode,
            max_context_chars=max_context_chars,
            max_examples=max_eval_examples,
            seed=seed + 1,
        )

    @staticmethod
    def _load(
        dataset_name: str,
        dataset_config: str,
        split: str,
        context_mode: str,
        max_context_chars: int,
        max_examples: int,
        seed: int,
    ) -> List[Dict[str, str]]:
        ds: Dataset = load_dataset(dataset_name, dataset_config, split=split)
        if max_examples > 0 and max_examples < len(ds):
            ds = ds.shuffle(seed=seed).select(range(max_examples))

        rows: List[Dict[str, str]] = []
        for ex in ds:
            q = str(ex.get("question") or "").strip()
            a = str(ex.get("answer") or "").strip()
            c = build_hotpot_context(ex, mode=context_mode, max_context_chars=max_context_chars)
            if not q or not a or not c:
                continue
            rows.append({"query": q, "answer": a, "context": c})
        return rows

    def build_prompt(self, query: str, context: str) -> str:
        body = self.prompt_template.format(query=query, context=context)
        return f"{self.format_instruction}\n\n{body}"

    def sample_train(self, n: int) -> List[Dict[str, str]]:
        idx = [self.rng.randrange(len(self.train_data)) for _ in range(n)]
        return [self.train_data[i] for i in idx]

    def sample_eval(self, n: int) -> List[Dict[str, str]]:
        if n <= 0 or n >= len(self.eval_data):
            return list(self.eval_data)
        idx = [self.rng.randrange(len(self.eval_data)) for _ in range(n)]
        return [self.eval_data[i] for i in idx]


def get_torch_dtype(dtype: str) -> Any:
    if dtype == "bfloat16":
        return torch.bfloat16
    if dtype == "float16":
        return torch.float16
    if dtype == "float32":
        return torch.float32
    return "auto"


def build_model_kwargs(args: argparse.Namespace, torch_dtype: Any) -> Dict[str, Any]:
    sig = inspect.signature(AutoModelForCausalLM.from_pretrained)
    kwargs: Dict[str, Any] = {
        "trust_remote_code": args.trust_remote_code,
        "local_files_only": args.local_files_only,
    }
    if torch_dtype != "auto":
        if "dtype" in sig.parameters:
            kwargs["dtype"] = torch_dtype
        else:
            kwargs["torch_dtype"] = torch_dtype
    return kwargs


def load_models(args: argparse.Namespace):
    torch_dtype = get_torch_dtype(args.dtype)
    model_kwargs = build_model_kwargs(args, torch_dtype=torch_dtype)

    tokenizer = AutoTokenizer.from_pretrained(
        args.model_name_or_path,
        trust_remote_code=args.trust_remote_code,
        local_files_only=args.local_files_only,
    )
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    policy = AutoModelForCausalLM.from_pretrained(args.model_name_or_path, **model_kwargs)
    policy.to(args.device)
    policy.train()

    ref_path = args.reference_model_name_or_path or args.model_name_or_path
    ref = AutoModelForCausalLM.from_pretrained(ref_path, **model_kwargs)
    ref.to(args.device)
    ref.eval()
    for p in ref.parameters():
        p.requires_grad = False
    return policy, ref, tokenizer


def parse_completion(
    completion: str,
    think_open: str,
    think_close: str,
    answer_start: str,
    answer_end: str,
) -> Tuple[int, str, str]:
    text = strip_meta(completion)

    i_think_open = text.find(think_open)
    i_think_close = text.find(think_close, i_think_open + len(think_open)) if i_think_open >= 0 else -1
    i_answer_start = text.find(answer_start)
    i_answer_end = text.find(answer_end, i_answer_start + len(answer_start)) if i_answer_start >= 0 else -1

    format_ok = int(
        i_think_open >= 0
        and i_think_close > i_think_open
        and i_answer_start > i_think_close
        and i_answer_end > i_answer_start
    )

    thinking = ""
    answer = ""
    if i_think_open >= 0 and i_think_close > i_think_open:
        thinking = text[i_think_open + len(think_open) : i_think_close].strip()
    if i_answer_start >= 0 and i_answer_end > i_answer_start:
        answer = text[i_answer_start + len(answer_start) : i_answer_end].strip()
    return format_ok, thinking, answer


@torch.no_grad()
def generate_grouped_completions(
    model,
    tokenizer,
    prompts: Sequence[str],
    group_size: int,
    max_prompt_tokens: int,
    max_new_tokens: int,
    temperature: float,
    top_p: float,
    top_k: int,
    answer_end_token: str,
    device: str,
) -> List[List[str]]:
    flat_prompts: List[str] = []
    for p in prompts:
        flat_prompts.extend([p] * group_size)

    enc = tokenizer(
        flat_prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_prompt_tokens,
        add_special_tokens=False,
    )
    enc = {k: v.to(device) for k, v in enc.items()}

    eos_ids = [tokenizer.eos_token_id]
    answer_end_id = tokenizer.convert_tokens_to_ids(answer_end_token) if answer_end_token else None
    if isinstance(answer_end_id, int) and answer_end_id >= 0 and answer_end_id != tokenizer.unk_token_id:
        eos_ids.append(answer_end_id)
    eos_ids = [x for x in dict.fromkeys(eos_ids) if x is not None]
    eos_arg: Any = eos_ids[0] if len(eos_ids) == 1 else eos_ids

    out = model.generate(
        **enc,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=eos_arg,
    )
    gen = out[:, enc["input_ids"].shape[1] :]
    texts = tokenizer.batch_decode(gen, skip_special_tokens=False)

    grouped: List[List[str]] = []
    idx = 0
    for _ in prompts:
        grouped.append(texts[idx : idx + group_size])
        idx += group_size
    return grouped


def compute_logps(
    model,
    tokenizer,
    prompts: Sequence[str],
    completions: Sequence[str],
    max_prompt_tokens: int,
    max_new_tokens: int,
    device: str,
    requires_grad: bool,
) -> torch.Tensor:
    full_texts = [p + c for p, c in zip(prompts, completions)]
    max_len = max_prompt_tokens + max_new_tokens

    enc_full = tokenizer(
        full_texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_len,
        add_special_tokens=False,
    )
    prompt_enc = tokenizer(
        list(prompts),
        return_tensors=None,
        padding=False,
        truncation=True,
        max_length=max_len,
        add_special_tokens=False,
    )

    input_ids = enc_full["input_ids"].to(device)
    attention_mask = enc_full["attention_mask"].to(device)
    prompt_lens = [len(x) for x in prompt_enc["input_ids"]]

    cm = torch.enable_grad() if requires_grad else torch.no_grad()
    with cm:
        logits = model(input_ids=input_ids, attention_mask=attention_mask).logits
        logprobs = torch.log_softmax(logits[:, :-1, :], dim=-1)
        target = input_ids[:, 1:]
        token_logp = torch.gather(logprobs, dim=-1, index=target.unsqueeze(-1)).squeeze(-1)

        seq_logp: List[torch.Tensor] = []
        bsz = input_ids.size(0)
        for i in range(bsz):
            seq_len = int(attention_mask[i].sum().item())
            prompt_len = min(prompt_lens[i], seq_len)
            if seq_len <= prompt_len:
                seq_logp.append(token_logp.new_zeros(()))
                continue
            start = max(0, prompt_len - 1)
            end = seq_len - 1
            seq_logp.append(token_logp[i, start:end].sum())
        return torch.stack(seq_logp, dim=0)


def flatten_grouped(
    prompts: Sequence[str],
    gold_answers: Sequence[str],
    grouped_completions: Sequence[Sequence[str]],
    think_open: str,
    think_close: str,
    answer_start: str,
    answer_end: str,
    format_weight: float,
    em_weight: float,
) -> Dict[str, Any]:
    flat_prompts: List[str] = []
    flat_completions: List[str] = []
    rewards: List[float] = []
    format_rewards: List[float] = []
    em_rewards: List[float] = []
    group_ids: List[int] = []

    for gi, (p, g, comps) in enumerate(zip(prompts, gold_answers, grouped_completions)):
        for c in comps:
            fmt, _, parsed_answer = parse_completion(
                completion=c,
                think_open=think_open,
                think_close=think_close,
                answer_start=answer_start,
                answer_end=answer_end,
            )
            em = exact_match(parsed_answer, g) if parsed_answer else 0.0
            rew = format_weight * float(fmt) + em_weight * float(em)

            flat_prompts.append(p)
            flat_completions.append(c)
            rewards.append(rew)
            format_rewards.append(float(fmt))
            em_rewards.append(float(em))
            group_ids.append(gi)

    return {
        "prompts": flat_prompts,
        "completions": flat_completions,
        "rewards": rewards,
        "format_rewards": format_rewards,
        "em_rewards": em_rewards,
        "group_ids": group_ids,
    }


def group_normalized_advantages(rewards: torch.Tensor, group_ids: Sequence[int], eps: float) -> torch.Tensor:
    out = torch.zeros_like(rewards)
    groups: Dict[int, List[int]] = defaultdict(list)
    for i, gid in enumerate(group_ids):
        groups[int(gid)].append(i)
    for _, idxs in groups.items():
        r = rewards[idxs]
        mean = r.mean()
        std = r.std(unbiased=False)
        out[idxs] = (r - mean) / (std + eps)
    return out


@torch.no_grad()
def evaluate(
    env: HotpotReasoningEnv,
    model,
    tokenizer,
    args: argparse.Namespace,
) -> Dict[str, float]:
    batch = env.sample_eval(args.eval_prompts)
    prompts = [env.build_prompt(x["query"], x["context"]) for x in batch]
    golds = [x["answer"] for x in batch]

    grouped = generate_grouped_completions(
        model=model,
        tokenizer=tokenizer,
        prompts=prompts,
        group_size=1,
        max_prompt_tokens=args.max_prompt_tokens,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_p=args.top_p,
        top_k=args.top_k,
        answer_end_token=args.answer_end_token,
        device=args.device,
    )
    completions = [g[0] for g in grouped]
    parsed = [
        parse_completion(
            completion=c,
            think_open=args.think_open_token,
            think_close=args.think_close_token,
            answer_start=args.answer_start_token,
            answer_end=args.answer_end_token,
        )
        for c in completions
    ]
    fmt = [x[0] for x in parsed]
    ans = [x[2] for x in parsed]
    em = [exact_match(a, g) if a else 0.0 for a, g in zip(ans, golds)]
    return {
        "eval_format_rate": float(sum(fmt) / max(1, len(fmt))),
        "eval_em_rate": float(sum(em) / max(1, len(em))),
        "eval_reward": float(
            (args.format_reward_weight * sum(fmt) + args.em_reward_weight * sum(em)) / max(1, len(fmt))
        ),
    }


def save_checkpoint(model, tokenizer, output_dir: str, step: int, stats: Dict[str, Any]) -> None:
    ckpt_dir = os.path.join(output_dir, f"checkpoint-{step:06d}")
    os.makedirs(ckpt_dir, exist_ok=True)
    model.save_pretrained(ckpt_dir)
    tokenizer.save_pretrained(ckpt_dir)
    with open(os.path.join(ckpt_dir, "rl_stats.json"), "w", encoding="utf-8") as fh:
        json.dump(stats, fh, indent=2, ensure_ascii=False)


def main() -> None:
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    set_seed(args.seed)

    env = HotpotReasoningEnv(
        dataset_name=args.dataset_name,
        dataset_config=args.dataset_config,
        train_split=args.train_split,
        eval_split=args.eval_split,
        context_mode=args.context_mode,
        max_context_chars=args.max_context_chars,
        prompt_template=args.prompt_template,
        format_instruction=args.format_instruction,
        max_train_examples=args.max_train_examples,
        max_eval_examples=args.max_eval_examples,
        seed=args.seed,
    )
    if len(env.train_data) == 0:
        raise RuntimeError("Empty Hotpot train environment.")

    policy, ref, tokenizer = load_models(args)
    optimizer = AdamW(policy.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)

    run_history: List[Dict[str, Any]] = []
    pbar = tqdm(range(1, args.num_steps + 1), desc=f"RL-{args.algorithm}", unit="step")
    for step in pbar:
        batch = env.sample_train(args.prompts_per_step)
        prompts = [env.build_prompt(x["query"], x["context"]) for x in batch]
        golds = [x["answer"] for x in batch]

        grouped = generate_grouped_completions(
            model=policy,
            tokenizer=tokenizer,
            prompts=prompts,
            group_size=args.group_size,
            max_prompt_tokens=args.max_prompt_tokens,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
            top_p=args.top_p,
            top_k=args.top_k,
            answer_end_token=args.answer_end_token,
            device=args.device,
        )

        flat = flatten_grouped(
            prompts=prompts,
            gold_answers=golds,
            grouped_completions=grouped,
            think_open=args.think_open_token,
            think_close=args.think_close_token,
            answer_start=args.answer_start_token,
            answer_end=args.answer_end_token,
            format_weight=args.format_reward_weight,
            em_weight=args.em_reward_weight,
        )

        rewards_t = torch.tensor(flat["rewards"], dtype=torch.float32, device=args.device)
        adv_t = group_normalized_advantages(rewards_t, flat["group_ids"], eps=args.adv_eps)

        logp = compute_logps(
            model=policy,
            tokenizer=tokenizer,
            prompts=flat["prompts"],
            completions=flat["completions"],
            max_prompt_tokens=args.max_prompt_tokens,
            max_new_tokens=args.max_new_tokens,
            device=args.device,
            requires_grad=True,
        )
        logp_ref = compute_logps(
            model=ref,
            tokenizer=tokenizer,
            prompts=flat["prompts"],
            completions=flat["completions"],
            max_prompt_tokens=args.max_prompt_tokens,
            max_new_tokens=args.max_new_tokens,
            device=args.device,
            requires_grad=False,
        )

        kl_term = logp - logp_ref
        if args.algorithm == "grpo":
            objective = adv_t.detach() * logp - args.beta_kl * kl_term
        else:
            log_ratio = torch.clamp(logp - logp_ref.detach(), min=-20.0, max=20.0)
            ratio = torch.exp(log_ratio)
            clipped = torch.clamp(ratio, 1.0 - args.cispo_clip_eps, 1.0 + args.cispo_clip_eps)
            surrogate = torch.minimum(ratio * adv_t.detach(), clipped * adv_t.detach())
            objective = surrogate - args.beta_kl * kl_term

        loss = -objective.mean()
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        if args.grad_clip_norm > 0:
            torch.nn.utils.clip_grad_norm_(policy.parameters(), args.grad_clip_norm)
        optimizer.step()

        train_metrics = {
            "step": step,
            "loss": float(loss.item()),
            "reward_mean": float(rewards_t.mean().item()),
            "reward_std": float(rewards_t.std(unbiased=False).item()),
            "format_rate": float(sum(flat["format_rewards"]) / max(1, len(flat["format_rewards"]))),
            "em_rate": float(sum(flat["em_rewards"]) / max(1, len(flat["em_rewards"]))),
            "mean_kl_proxy": float(kl_term.detach().mean().item()),
        }
        run_history.append(train_metrics)
        pbar.set_postfix(
            loss=f"{train_metrics['loss']:.4f}",
            reward=f"{train_metrics['reward_mean']:.3f}",
            em=f"{train_metrics['em_rate']:.3f}",
            fmt=f"{train_metrics['format_rate']:.3f}",
        )

        if step % args.log_every == 0:
            print(json.dumps(train_metrics, ensure_ascii=False))

        if args.eval_every > 0 and step % args.eval_every == 0:
            eval_metrics = evaluate(env=env, model=policy, tokenizer=tokenizer, args=args)
            row = {"step": step, **eval_metrics}
            run_history.append(row)
            print(json.dumps(row, ensure_ascii=False))

        if args.save_every > 0 and step % args.save_every == 0:
            stats = {
                "step": step,
                "algorithm": args.algorithm,
                "last_train_metrics": train_metrics,
            }
            save_checkpoint(policy, tokenizer, args.output_dir, step=step, stats=stats)

    final_stats = {
        "algorithm": args.algorithm,
        "num_steps": args.num_steps,
        "final_step": args.num_steps,
        "last_metrics": run_history[-1] if run_history else {},
        "args": vars(args),
    }
    save_checkpoint(policy, tokenizer, args.output_dir, step=args.num_steps, stats=final_stats)
    with open(os.path.join(args.output_dir, "rl_history.jsonl"), "w", encoding="utf-8") as fh:
        for row in run_history:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
    with open(os.path.join(args.output_dir, "final_stats.json"), "w", encoding="utf-8") as fh:
        json.dump(final_stats, fh, indent=2, ensure_ascii=False)

    print(json.dumps(final_stats, indent=2, ensure_ascii=False))
    print(f"Saved RL run to {args.output_dir}")


if __name__ == "__main__":
    main()
